add chapter4
hantmac/Mastering_Go_Second_Edition_Zh_CN pull request #15
Opened 2020-04-05 17:09 UTC by newlife

2020-04-05 18:08 UTC, calmbryan commented on eBook/chapter4/04.2.1.md
> +相对于直接手动初始化一个结构体变量，函数`createStructure()`提供了一种更加优雅的方法来创建结构体变量。这种方式不仅能够检查提供给结构体字段的值是否正确和有效。另外，当定义的结构体当出问题之后，你能够很快找到问题所在，因为知道这个变量是在哪里被初始化的，去哪里找问题。注意有些人可能更喜欢把该函数命名为`NewStructure()`。
- > 这种方式不仅能够检查提供给结构体字段的值是否正确和有效，还能在定义的结构体出现问题之后很快找到问题所在，因为我们知道这个变量是在哪里被初始化的。

2020-04-05 18:14 UTC, calmbryan commented on eBook/chapter4/04.2.md
> +另外，你可以通过字段的名字来访问这个字段。所有，为了获取变量`s1`的`person`字段的值，你可以输入`s1.person`。
所有 -> 所以

2020-04-05 18:18 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +min,_ := strconv.ParseFloat(arguments[1], 64)
```suggestion
min, _ := strconv.ParseFloat(arguments[1], 64)
```

2020-04-05 18:19 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +	return 2 * x, x*x,-x
```suggestion
	return 2 * x, x*x, -x
```

2020-04-05 18:19 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +`retThree()`函数返回了包含三个整数元素的元组，这种能力使得函数能够返回多个数据，无需将它们聚合到结构体重，然后返回一个结构体变量。
```suggestion
`retThree()`函数返回了包含三个整数元素的元组，这种能力使得函数能够返回多个数据，无需将它们聚合到结构体中，然后返回一个结构体变量。
```

2020-04-05 18:20 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +这里我们使用了两次`retThree()`函数。第一次我没让你并没有将其返回值保存，第二次使用三个变量保存返回值，在Go的术语中这叫做元组赋值，看到这里，你是不是有了一种`Go支持元组！`的错觉。
第一次我没让你并没有将其返回值保存 --> 第一次我们并没有将其返回值保存

2020-04-05 18:21 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +如果有些返回值你并不关心，可以使用`_`操作符忽略掉它们。要知道，在Go的代码里声明了但是未使用的代码是会导致编译错误的。
```suggestion
如果有些返回值你并不关心，可以使用`_`操作符忽略掉它们。要知道，在Go的代码里声明了但是未使用的变量是会导致编译错误的。
```

2020-04-05 18:22 UTC, calmbryan commented on eBook/chapter4/04.3.md
> +	fmt.Println(x1,x2,x3)
```suggestion
	x1, x2, x3 := n1*2, n1*n1, -n1
	fmt.Println(x1, x2, x3)
```

2020-04-05 18:23 UTC, calmbryan commented on eBook/chapter4/04.4.1.md
> +每一个正则表达式都通过构建一种叫做**有限自动机**的状态转换图表，被编译成识别器。一个有限自动机可以使确定性的也可以是不确定性的。不确定性的意思是一种输入可能会产生多种输出状态。识别器是一种程序，它接收一个字符串`x`并且能够分辨出`x`是否是给定语言的一个句子。
一个有限自动机可以使确定性的也可以是不确定性的 -- > 可以是

2020-04-05 18:33 UTC, calmbryan commented on eBook/chapter4/04.4.3.md
> +				fmt.Printf(strings.Replace(line,match[1],newFormat,1))
```suggestion
				fmt.Printf(strings.Replace(line, match[1], newFormat,1))
```

2020-04-05 18:39 UTC, calmbryan commented on eBook/chapter4/04.4.md
> +Go标准库中`regexp`包负责定义正则表达式和模式匹配。你会在本章后面的部分看到这个包的时候。
你会在本章后面的部分看到这个包的时候。-->  你会在本章后面的部分看到这个包

2020-04-05 18:51 UTC, calmbryan commented on eBook/chapter4/04.5.3.md
> +`strings.Compare()`函数用于比较两个字符串是否相等，相等返回`true`，否则返回1或者-1（strings.Compare(a,b),如果a<b则返回1，a<b返回-1,所谓a>b,意思是出现在字母表中的顺序，译者加）。
官方文档：The result will be 0 if a==b, -1 if a < b, and +1 if a > b.
```suggestion
`strings.Compare()`函数用于比较两个字符串是否相等，相等返回`true`，否则返回1或者-1（strings.Compare(a,b),如果 a<b 则返回 -1，如果 a>b 则返回 1，所谓a>b，意思是出现在字母表中的顺序，译者加）。
```

2020-04-05 18:55 UTC, calmbryan commented on eBook/chapter4/04.5.3.md
> +最后两个语句定义了一个**trim函数**，这个函数可保留你字符串感兴趣的rune。这个函数作为函数` strings.TrimFunc()`的第二个参数（就是一个过滤函数）。
这个函数可保留你字符串感兴趣的rune --> 这个函数可保留字符串中感兴趣的rune

2020-04-05 19:06 UTC, calmbryan commented on eBook/chapter4/04.8.md
> +本节你将学习使用Go实现**K-V存储**的简单实现，也就是如何实现K-v存储的核心功能。K-V存储的目标是易于简单的：尽可能快速地发出请求并给出响应。也就是使用简答的算法和简单的数据结构实现这些功能。
K-V

2020-04-05 19:14 UTC, calmbryan commented on eBook/chapter4/04.8.md
> +这部分代码处理用户的输入。`switch`的使用使得程序的设计看上去十分清晰，能够避免使用讴歌`if...else`语句。
```suggestion
这部分代码处理用户的输入。`switch`的使用使得程序的设计看上去十分清晰，能够避免使用过多`if...else`语句。
```

2020-04-05 19:28 UTC, calmbryan commented on eBook/chapter4/4.10.md
> +这里使用的函数`MarshalIndent()`，也可以处理JSON数据(`encoding/json`包中也有这个函数)，和`Marshal()`函数差不多，区别在于每一个XML元素都单读一行，并且根据这个元素的层级深度确定缩进个数。这个函数主要处理XML数据的显式，不处理值。
显式 --> 显示

2020-04-05 19:30 UTC, calmbryan commented on eBook/chapter4/4.14.md
> +在下一章中，你将学习使用更加高级的数据结构来组织和操作数据，比如二叉树，链表，双向链表，队列，栈，哈希表。你还会发现`container`标准库中的数据结构，如何进行矩阵操作，如何确认数独谜题。下一章最后的主题将是**随机数**，将生成难以破解的密码字符串。
```suggestion
在下一章中，你将学习使用更加高级的数据结构来组织和操作数据，比如二叉树，链表，双向链表，队列，栈，哈希表。你还会发现`container`标准库中的数据结构，如何进行矩阵操作，如何确认数独谜题。下一章最后的主题是**随机数**，将生成难以破解的密码字符串。
```

2020-04-05 19:31 UTC, calmbryan commented on eBook/chapter4/4.10.md
> +我们先把读取的文件转成JSON，然后把这些数据放到一个Go的结构体中。然后，我们修改这个结构体的内容做了一点修改，接着用函数` MarshalIndent() `把这个数据转换为XML格式，用`xml.Header()`给这个数据加了一个header。
我们修改这个结构体的内容做了一点修改 --> 我们对这个结构体的内容做了一点修改

2020-04-06 02:09 UTC, hantmac requested changes

2020-04-06 02:09 UTC, hantmac commented on eBook/chapter4/04.4.2.md
> +你将在第8章中学习到`bufio.ReadString()`函数，这个函数会读取文件知道遇到参数。所以`bufio.ReadString('\n')`的意思就是逐行读取文本文件，因为`\n`在UNIX系统中是换行符。`bufio.ReadString()`函数返回的是字节切片。
`这个函数会读取文件知道遇到参数`=>`这个函数会读取文件直到遇到所给标识参数，比如 '\n' `

2020-04-27 15:01 UTC, merged