Chapter9
hantmac/Mastering_Go_Second_Edition_Zh_CN pull request #8
Opened 2020-03-24 00:27 UTC by calmbryan

Finished Chapter9
基本完成第九章的翻译工作。
添加.gitignore  包含MacOS, Windows, vscode相关。

2020-03-24 15:28 UTC, hantmac requested changes
👍

2020-03-24 15:28 UTC, hantmac commented on eBook/chapter9/09.1.1.md
> +Unix内核调度负责程序线程的执行。另一方面，Go运行时也有自己的调度程序，它使用称为 `m:n scheduling` 的调度技术负责执行`goroutine`，通过多路复用使n个操作系统线程执行m个`goroutine`。Go调度器是Go中负责Go程序中`goroutine`的执行方式和执行顺序的组件。这使得Go调度器成为Go编程语言中非常重要的一部分，因为Go程序中的所有都是作为`goro
`因为Go程序中的所有都是作为`goroutine`执行的。`=> `因为所有的Go程序都是以`goroutine`的形式执行的。`

2020-03-24 15:28 UTC, hantmac commented on eBook/chapter9/09.11.md
> +下章将通过介绍 `select` 关键字来继续讨论 Go 的并发。这个关键字可以让通道执行许多有趣的任务，我想您会真正的被它的强大所震惊。
`我想您会真正的被它的强大所震惊。`=>`你会被它的强大所震惊。`

2020-03-24 15:28 UTC, hantmac commented on eBook/chapter9/09.3.1.md
> +这次问题的根源也非常清楚：`panic: sync: anic: sync: negative WaitGroup counter`。虽然这两种情况下的错误消息都非常具体，可以帮助您解决实际的问题，但是你应该非常小心地处理放入程序中的`sync.Add()`和`sync.Done()`调用的数量。另外，请注意，第二个错误情况(`panic: sync: anic: sync: negative
`panic: sync: anic: sync: negative`=>`panic: sync: negative`

2020-03-24 15:28 UTC, hantmac commented on eBook/chapter9/09.4.4.md
> +a.go:13:7: invalid operation: out <- i(send to receive-only type <-chan int)
我觉得这里原文写错了，`in`是一个只读通道(receive-only)，`out`是只写通道(write-only)，应该改成 ` a.go:13:7: invalid operation: out <- i(send to receive-only type <-chan int)`=> `a.go:13:7: invalid operation: in <- i(send to receive-only type <-chan int)`
`a.go:15:7: invalid operation: close(in)(cannot close receive-only channel)`

2020-03-24 16:50 UTC, calmbryan commented on eBook/chapter9/09.4.4.md
> +a.go:13:7: invalid operation: out <- i(send to receive-only type <-chan int)
确实。

2020-03-25 08:03 UTC, hantmac approved these changes

2020-03-25 08:03 UTC, merged