[+] finish 02.0 - 02.2
hantmac/Mastering_Go_Second_Edition_Zh_CN pull request #9
Opened 2020-03-27 08:57 UTC by random-yang

2020-03-27 08:57 UTC, random-yang commented
这只是一部分，剩下的翻译中。。。

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.0.md
> +您在上一章中学到的所有 Go 功能都非常方便，您将一直使用它们。但是，更有价值的是看到和理解这背后发生的事情以及 Go 在幕后的操作方式。
我觉得还是把`您`统一换成`你`,比较好

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.0.md
> +此外，您还将学习如何从您的 C 代码中调用 Go 函数，以及如何使用`panic()`和`restore()`函数和`defer`关键字。
`您还将学习如何从您的 C 代码中调用 Go 函数，`=>`你还将学习如何从C 代码中调用 Go 函数，`

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.1.md
> +本章的最后讨论汇编语言和节点树的时候，你还会学到 一个更多有用的`go tool compile`命令。不过目前您可以尝试一下下面的命令：
`你还会学到 一个更多` 多了个空格

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.2.1.md
> +Go 垃圾收集器的操作基于三色算法。
`Go 垃圾收集器的操作基于三色算法。`=> `Go 基于三色算法的垃圾回收器。`

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.2.1.md
> +![]()
图片的话可以先截图，然后上传到图床，推荐一个好用的图床工具 https://github.com/Molunerfinn/PicGo

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.2.5.md
> +现在您已经看到了`unsafe`包在起作用，现在是时候讨论更多有关使其成为特殊程序包了。首先，如果您查看`unsafe`包的源代码，您可能会有些惊讶。在使用 Homebrew(https://brew.sh/)安装的 Go 版本为 1.11.4 的 macOS Mojave 系统上，`unsafe`包的源代码位于`/usr/local/Cellar/go/1.11.4/libexec/src/u
`现在是时候讨论更多有关使其成为特殊程序包了` 不是很通顺

2020-03-27 15:40 UTC, hantmac commented on eBook/chapter2/02.2.md
> +_垃圾回收是和 go 线程同时运行的，它是类型精确的，而且多个垃圾回收线程可以并行运行。它是一种使用了写屏障的并发标记清除的垃圾回收方式。它是非分代和非压缩的。使用按 P 分配区域隔离的大小来完成分配，以最小化碎片，同时消除常见情况下的锁。_
`go 线程`=> `goroutine`

2020-03-27 16:30 UTC, random-yang commented on eBook/chapter2/02.0.md
> +您在上一章中学到的所有 Go 功能都非常方便，您将一直使用它们。但是，更有价值的是看到和理解这背后发生的事情以及 Go 在幕后的操作方式。
嗯嗯，好的。

2020-03-28 01:55 UTC, random-yang commented on eBook/chapter2/02.2.1.md
> +![]()
Hi，请问这边图床是上传到自己的图床吗？

2020-03-28 06:23 UTC, hantmac commented on eBook/chapter2/02.2.1.md
> +![]()
可以的

2020-03-28 08:42 UTC, newlife commented on eBook/chapter2/02.0.md
> +此外，您还将学习如何从您的 C 代码中调用 Go 函数，以及如何使用`panic()`和`restore()`函数和`defer`关键字。
> 但是，您将不需要经常使用此功能...

**讨论：**

1. 但是---> 当然，这里没有明显的转折，“当然”是不是会更顺畅？
2. 将--->可能，这一句本来就含有“未来”的意思，"将"可以省略，换“可能”似乎更严谨
3. 前后句顺序是否调整更符合中文语法？
试译，
>当然，因为Go 是一种非常强大的编程语言，你可能不需要经常使用此功能。

2020-03-28 09:47 UTC, hantmac requested changes

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.3.2.md
> +好消息是你不需要做任何特别困难的事情，因为所有关键信息都包含在Go文件中。你唯一需要做的关键是编译C代码以创建一个库，该库需要执行以下命令：
`好消息是你不需要做任何特别困难的事情，因为所有关键信息都包含在Go文件中。你唯一需要做的关键是编译C代码以创建一个库` => `由于所有的关键信息都包含在Go文件中了，所有你唯一需要做的就是编译C代码以生成一个库`

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.3.md
> +尽管Go打算使你的编程体验更好，帮助你摆脱C的怪癖，但是C仍然是一种非常有用的编程语言。这意味着在某些情况下(例如，使用数据库或使用C编写的设备驱动程序)仍需要使用C，这意味着你将需要在Go项目中使用C代码。
`尽管Go打算使你的编程体验更好` = > `与C相比之下，尽管Go的编程体验更好`

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.4.1.md
> +> Tip: 你将在*第 6 章-你可能不了解 Go 软件包和 Go 函数*中了解有关 Go 软件包的更多信息。
`软件包`不用做翻译，直接`package`就行

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.4.1.md
> +必须先导出将由 C 代码调用的每个 Go 函数。这意味着你应在导出之前放置一个以`// export`开头的注释行。在`// export`的后面你将需要输入函数的名称，因为这是 C 代码将使用的名称。
`必须先导出将由 C 代码调用的每个 Go 函数` => `必须将C 代码准备调用的Go 函数导出`

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.4.2.md
> +  GoInt x = 12;
这部分的字体颜色怎么突然加深了

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.4.2.md
> +`GoInt p`变量是从 Go 函数获取整数值所必需的，该函数是使用`(int)p`表示法转换为 C 整数。
`GoInt p`表示使用`(int)p`转换为 C 整数变量，是从Go 函数获取整数值所必需的方式。

2020-03-28 09:47 UTC, hantmac commented on eBook/chapter2/02.5.md
> +你很可能会发现生成的输出非常复杂且难以理解，这证明如果代码不清晰，则操作和使用`defer`的结果可能会很棘手。让我解释一下结果，以便更好地了解如果你不密切关注代码的话，`defer`会变得多么棘手。
`让我解释一下结果，以便更好地了解如果你不密切关注代码的话，`defer`会变得多么棘手。`  感觉这句话没必要再翻译了，跟前一句有点重复

2020-03-28 09:57 UTC, random-yang commented on eBook/chapter2/02.3.2.md
> +好消息是你不需要做任何特别困难的事情，因为所有关键信息都包含在Go文件中。你唯一需要做的关键是编译C代码以创建一个库，该库需要执行以下命令：
=> 由于所有的关键信息都包含在Go文件中了，"**所以**"你唯一需要做的就是编译C代码以生成一个库

感觉这样更优一些。

2020-03-28 10:00 UTC, random-yang commented on eBook/chapter2/02.3.md
> +尽管Go打算使你的编程体验更好，帮助你摆脱C的怪癖，但是C仍然是一种非常有用的编程语言。这意味着在某些情况下(例如，使用数据库或使用C编写的设备驱动程序)仍需要使用C，这意味着你将需要在Go项目中使用C代码。
=> 与C相比~~之下~~，尽管Go的编程体验更好

2020-03-28 10:10 UTC, random-yang commented on eBook/chapter2/02.4.2.md
> +  GoInt x = 12;
我在本地的打开markdown渲染出来是没有问题，我猜测可能是在线的github markdown解析吧前面的两个**以为是要加粗了。

2020-03-28 10:13 UTC, random-yang commented on eBook/chapter2/02.4.2.md
> +`GoInt p`变量是从 Go 函数获取整数值所必需的，该函数是使用`(int)p`表示法转换为 C 整数。
=> `GoInt p`表示使用`(int)p`转换为 C 整数变量，是从 Go 函数获取整数值的必要方式。

2020-03-28 10:21 UTC, random-yang commented on eBook/chapter2/02.2.1.md
> +![]()
图片我在这章翻译完成后统一上传

2020-03-29 06:48 UTC, hantmac approved these changes
👍

2020-04-04 15:18 UTC, hantmac requested changes

2020-04-04 15:18 UTC, hantmac commented on eBook/chapter2/02.11.md
> +Go 节点是包含大量属性的结构。你将在第 4 章“复合类型的使用”中学习有关定义和使用 Go 结构的更多信息。Go 编译器的模块根据 Go 编程语言的语法对 Go 程序中的所有内容进行解析和分析。此分析的最终结果是一棵树，该树对应于所提供的 Go 代码，并以适合编译器而非开发人员的不同方式表示程序结构。
`Go 结构的更多信息`=>`Go struct 的更多内容`

2020-04-04 15:18 UTC, hantmac commented on eBook/chapter2/02.11.md
> +Go 节点是包含大量属性的结构。你将在第 4 章“复合类型的使用”中学习有关定义和使用 Go 结构的更多信息。Go 编译器的模块根据 Go 编程语言的语法对 Go 程序中的所有内容进行解析和分析。此分析的最终结果是一棵树，该树对应于所提供的 Go 代码，并以适合编译器而非开发人员的不同方式表示程序结构。
`并以适合编译器而非开发人员的不同方式表示程序结构。`=> `并以适合编译器的方式表示程序结构。`

2020-04-04 15:18 UTC, hantmac commented on eBook/chapter2/02.13.4.md
> +这里要注意的重要事情是此代码中没有 WebAssembly 的影子，并且 toWasm.go 可以单独编译和执行，这意味着它没有与 WebAssembly 相关的外部依赖关系。
`这里要注意的重要事情是此代码中没有 WebAssembly 的影子`=> `这里要注意的重要事情是此代码并没有用到WebAssembly `

2020-04-04 15:18 UTC, hantmac commented on eBook/chapter2/02.16.md
> +本章讨论了许多有趣的 Go 相关主题，包括有关 Go 垃圾收集器的理论和实践信息。如何从 Go 程序中调用 C 代码；方便但不那么好掌握的`defer`关键字； `panic()`和`recovery()`函数； `strace(1)`，`dtrace(1)`和 dtruss(1)`UNIX工具；使用`unsafe package`；如何从Go生成WebAssembly代码；和Go生成的汇编代码
这段的markdown格式有点问题

2020-04-05 02:06 UTC, random-yang commented
你好，我还有个疑问，图片上传到我自己的图床，感觉很不稳定，万一以后我的图床服务停止了，图片不就不可以访问了嘛。

2020-04-05 02:18 UTC, hantmac commented
@random-yang 不是传到你自己的图床服务器，有些公共的图床服务，像微博，七牛，都挺稳定的，问题不大

2020-04-05 03:45 UTC, hantmac approved these changes

2020-04-05 03:45 UTC, hantmac commented
@random-yang  按照格式更新下SUMMARY.md这个文件，这样的话gitbook就更新了

2020-04-05 04:58 UTC, hantmac approved these changes

2020-04-05 04:58 UTC, merged